import type { NavigationItem } from "./types"

export const adminNavItems: NavigationItem[] = [
  {
    id: "admin-dashboard",
    label: "Dashboard",
    labelKey: "dashboard",
    href: "/admin/dashboard",
    icon: "layout-dashboard",
    section: "main",
    matchPrefixes: ["/admin/dashboard"],
  },
  {
    id: "admin-inbox",
    label: "Inbox",
    labelKey: "inbox",
    href: "/admin/inbox",
    icon: "inbox",
    section: "main",
    badge: { type: "count", value: 2 },
  },
  {
    id: "admin-calendar",
    label: "Calendar",
    labelKey: "calendar",
    href: "/admin/calendar",
    icon: "calendar-days",
    section: "main",
  },
  {
    id: "admin-teachers",
    label: "Teachers",
    labelKey: "teachers",
    href: "/admin/teachers",
    icon: "graduation-cap",
    section: "main",
  },
  {
    id: "admin-students",
    label: "Students",
    labelKey: "students",
    href: "/admin/students",
    icon: "users",
    section: "main",
  },
  {
    id: "admin-attendance",
    label: "Attendance",
    labelKey: "attendance",
    href: "/admin/attendance",
    icon: "calendar-check",
    section: "main",
  },
  {
    id: "admin-finance",
    label: "Finance",
    labelKey: "finance",
    href: "/admin/finance",
    icon: "wallet",
    section: "main",
    children: [
      {
        id: "admin-finance-payments",
        label: "Fees Collection",
        labelKey: "feesCollection",
        href: "/admin/finance/payments",
        icon: "wallet",
        section: "main",
        matchPrefixes: ["/admin/finance/payments"],
      },
      {
        id: "admin-finance-expenses",
        label: "Expenses",
        labelKey: "expenses",
        href: "/admin/finance/expenses",
        icon: "wallet",
        section: "main",
        matchPrefixes: ["/admin/finance/expenses"],
      },
    ],
    matchPrefixes: ["/admin/finance"],
  },
  {
    id: "admin-notices",
    label: "Notice Board",
    labelKey: "notices",
    href: "/admin/notices",
    icon: "megaphone",
    section: "updates",
  },
]
