import type { NavigationItem } from "./types"

export const studentNavItems: NavigationItem[] = [
  {
    id: "student-dashboard",
    labelKey: "dashboard",
    href: "/student/dashboard",
    icon: "layout-dashboard",
    section: "main",
    matchPrefixes: ["/student", "/student/dashboard"],
  },
  {
    id: "student-schedule",
    labelKey: "schedule",
    href: "/student/schedule",
    icon: "clock-3",
    section: "main",
    matchPrefixes: ["/student/schedule"],
  },
  {
    id: "student-assignments",
    labelKey: "assignments",
    href: "/student/assignments",
    icon: "clipboard-list",
    section: "main",
    matchPrefixes: ["/student/assignments"],
  },
  {
    id: "student-grades",
    labelKey: "grades",
    href: "/student/grades",
    icon: "star",
    section: "main",
    matchPrefixes: ["/student/grades"],
  },
  {
    id: "student-exams",
    labelKey: "exams",
    href: "/student/exams",
    icon: "file-text",
    section: "main",
    matchPrefixes: ["/student/exams"],
  },
  {
    id: "student-attendance",
    labelKey: "attendance",
    href: "/student/attendance",
    icon: "calendar-check",
    section: "main",
    matchPrefixes: ["/student/attendance"],
  },
  {
    id: "student-notices",
    labelKey: "notices",
    href: "/student/notices",
    icon: "megaphone",
    section: "updates",
    matchPrefixes: ["/student/notices"],
  },
  {
    id: "student-calendar",
    labelKey: "calendar",
    href: "/student/calendar",
    icon: "calendar-days",
    section: "main",
    matchPrefixes: ["/student/calendar"],
  },
  {
    id: "student-profile",
    labelKey: "profile",
    href: "/student/profile",
    icon: "user",
    section: "updates",
    matchPrefixes: ["/student/profile"],
  },
]
