import type { TeacherCardData } from "@/components/teachers/list/teacher-card.types"

export const TEACHER_CARD_SHOWCASE_ITEMS: readonly TeacherCardData[] = [
  {
    avatarFallback: "AM",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg",
    email: "argen.maulie@studixschool.org",
    employeeId: "T-1001",
    messageLabel: "Ko'rish",
    name: "Argen Maulie",
    phone: "+62 812 3456 7890",
    socials: [
      { href: "https://t.me/argenmaulie", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281234567890", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Mathematics",
  },
  {
    avatarFallback: "BC",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/purple.jpg",
    email: "bella.cruz@studixschool.org",
    employeeId: "T-1002",
    messageLabel: "Ko'rish",
    name: "Bella Cruz",
    phone: "+62 813 2234 5567",
    socials: [
      { href: "https://t.me/bellacruz", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281322345567", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Social Studies - Civics",
  },
  {
    avatarFallback: "CV",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    email: "cliff.villiam@studixschool.org",
    employeeId: "T-1003",
    messageLabel: "Ko'rish",
    name: "Cliff Villiam",
    phone: "+62 811 5567 2345",
    socials: [
      { href: "https://t.me/cliffvilliam", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281155672345", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "English Language",
  },
  {
    avatarFallback: "DA",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/green.jpg",
    email: "dariah.ahmed@studixschool.org",
    employeeId: "T-1004",
    messageLabel: "Ko'rish",
    name: "Dariah Ahmed",
    phone: "+62 815 9876 5432",
    socials: [
      { href: "https://t.me/dariahahmed", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281598765432", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Social Studies - History",
  },
  {
    avatarFallback: "EP",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/orange.jpg",
    email: "esteban.parez@studixschool.org",
    employeeId: "T-1005",
    messageLabel: "Ko'rish",
    name: "Esteban Parez",
    phone: "+62 819 6543 2109",
    socials: [
      { href: "https://t.me/estebanparez", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281965432109", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Arts - Visual Arts",
  },
  {
    avatarFallback: "FG",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg",
    email: "francesca.gill@studixschool.org",
    employeeId: "T-1006",
    messageLabel: "Ko'rish",
    name: "Francesca Gill",
    phone: "+62 817 2233 4455",
    socials: [
      { href: "https://t.me/francescagill", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281722334455", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Physical Education",
  },
  {
    avatarFallback: "GA",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    email: "george.abraham@studixschool.org",
    employeeId: "T-1007",
    messageLabel: "Ko'rish",
    name: "George Abraham",
    phone: "+62 816 7788 9900",
    socials: [
      { href: "https://t.me/georgeabraham", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281677889900", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Mathematics - Algebra",
  },
  {
    avatarFallback: "HM",
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/purple.jpg",
    email: "hellen.martinez@studixschool.org",
    employeeId: "T-1008",
    messageLabel: "Ko'rish",
    name: "Hellen Martinez",
    phone: "+62 814 6677 8899",
    socials: [
      { href: "https://t.me/hellenmartinez", icon: "mingcute:telegram-line", label: "Telegram" },
      { href: "https://wa.me/6281466778899", icon: "mingcute:whatsapp-line", label: "WhatsApp" },
    ],
    subject: "Science - Biology",
  },
] as const
