import type { StudentListItem } from "@/components/students/list/students-list.types"

export const STUDENTS_LIST_ITEMS: readonly StudentListItem[] = [
  {
    attendancePercentage: 95,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    classLabel: "7A",
    gpa: 3.8,
    id: "student-1001",
    name: "Michael Chen",
    performance: "good",
    status: "active",
    studentCode: "S-2101",
  },
  {
    attendancePercentage: 87,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/orange.jpg",
    classLabel: "7B",
    gpa: 2.9,
    id: "student-1002",
    name: "Emma Williams",
    performance: "needsSupport",
    status: "active",
    studentCode: "S-2102",
  },
  {
    attendancePercentage: 72,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg",
    classLabel: "7C",
    gpa: 2.4,
    id: "student-1003",
    name: "Rajesh Kumar",
    performance: "atRisk",
    status: "onLeave",
    studentCode: "S-2103",
  },
  {
    attendancePercentage: 93,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/purple.jpg",
    classLabel: "8A",
    gpa: 3.6,
    id: "student-1004",
    name: "Hannah Lee",
    performance: "good",
    status: "active",
    studentCode: "S-2104",
  },
  {
    attendancePercentage: 81,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/green.jpg",
    classLabel: "8B",
    gpa: 2.7,
    id: "student-1005",
    name: "Thomas Green",
    performance: "needsSupport",
    status: "active",
    studentCode: "S-2105",
  },
  {
    attendancePercentage: 97,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    classLabel: "8C",
    gpa: 3.9,
    id: "student-1006",
    name: "Isabella Rossi",
    performance: "good",
    status: "active",
    studentCode: "S-2106",
  },
  {
    attendancePercentage: 68,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg",
    classLabel: "9A",
    gpa: 2.3,
    id: "student-1007",
    name: "Ahmed Ali",
    performance: "atRisk",
    status: "onLeave",
    studentCode: "S-2107",
  },
  {
    attendancePercentage: 91,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/purple.jpg",
    classLabel: "9B",
    gpa: 3.5,
    id: "student-1008",
    name: "Chloe Davis",
    performance: "good",
    status: "active",
    studentCode: "S-2108",
  },
  {
    attendancePercentage: 90,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/green.jpg",
    classLabel: "7A",
    gpa: 3.7,
    id: "student-1009",
    name: "Sofia Martinez",
    performance: "good",
    status: "active",
    studentCode: "S-2109",
  },
  {
    attendancePercentage: 84,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/orange.jpg",
    classLabel: "7B",
    gpa: 3.0,
    id: "student-1010",
    name: "Noah Carter",
    performance: "needsSupport",
    status: "active",
    studentCode: "S-2110",
  },
  {
    attendancePercentage: 74,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    classLabel: "7C",
    gpa: 2.5,
    id: "student-1011",
    name: "Yusuf Karim",
    performance: "needsSupport",
    status: "suspended",
    studentCode: "S-2111",
  },
  {
    attendancePercentage: 89,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/blue.jpg",
    classLabel: "8A",
    gpa: 3.4,
    id: "student-1012",
    name: "Mia Johnson",
    performance: "good",
    status: "active",
    studentCode: "S-2112",
  },
  {
    attendancePercentage: 79,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/purple.jpg",
    classLabel: "8B",
    gpa: 2.8,
    id: "student-1013",
    name: "Victor Silva",
    performance: "needsSupport",
    status: "active",
    studentCode: "S-2113",
  },
  {
    attendancePercentage: 96,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/green.jpg",
    classLabel: "8C",
    gpa: 3.9,
    id: "student-1014",
    name: "Amina Yusuf",
    performance: "good",
    status: "active",
    studentCode: "S-2114",
  },
  {
    attendancePercentage: 70,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/orange.jpg",
    classLabel: "9A",
    gpa: 2.1,
    id: "student-1015",
    name: "Daniel Scott",
    performance: "atRisk",
    status: "suspended",
    studentCode: "S-2115",
  },
  {
    attendancePercentage: 92,
    avatarUrl: "https://heroui-assets.nyc3.cdn.digitaloceanspaces.com/avatars/red.jpg",
    classLabel: "9B",
    gpa: 3.6,
    id: "student-1016",
    name: "Layla Khan",
    performance: "good",
    status: "active",
    studentCode: "S-2116",
  },
] as const
